In [1]:
import numpy as np

#RESHAPE FUNCTION

In [5]:
arr=np.random.randint(1,15,(3,4))
print(arr.shape)
arr=arr.reshape(4,3)
print(arr)

(3, 4)
[[10  3  9]
 [ 1  7  5]
 [ 1 14 14]
 [ 6  8 10]]


#LINESPACE FUNCTION

In [7]:
np.linspace(1,18,5)

array([ 1.  ,  5.25,  9.5 , 13.75, 18.  ])

#FLATTEN FUNCTION


In [10]:
arr=np.random.randint(1,15,(3,4))
print(arr.shape)
print(arr)
print('-'*76)
arr=arr.flatten()
print(arr.shape)
print(arr)


(3, 4)
[[13 11  6  4]
 [ 6  8 12 13]
 [10 10  4  3]]
----------------------------------------------------------------------------
(12,)
[13 11  6  4  6  8 12 13 10 10  4  3]


#LOGSPACE FUNCTION


In [12]:
print(np.logspace(2,4,10, base=2))

[ 4.          4.66611616  5.44316     6.34960421  7.4069977   8.64047791
 10.0793684  11.75787594 13.71590373 16.        ]


#COPY FUNCTION



In [17]:
arr1=np.random.randint(1,15,10)

arr2=arr1
print(arr1,id(arr1))
print(arr2,id(arr2))
print('-'*30)
arr1=np.random.randint(1,15,10)
arr2=np.copy(arr1)
print(arr1,id(arr1))
print(arr2,id(arr2))



[ 9 14  6  7 14  1  9  5  8 10] 2124109887312
[ 9 14  6  7 14  1  9  5  8 10] 2124109887312
------------------------------
[14 14 10  5  5  6  5 13  7  6] 2124109887504
[14 14 10  5  5  6  5 13  7  6] 2124090515760


#MAX,MIN,SUM FNCS

In [23]:
arr1=np.random.randint(1,15,10)
print(arr)
print("max:",arr.max())
print("min:",arr.min())
print("sum:",arr.sum())


[13 11  6  4  6  8 12 13 10 10  4  3]
max: 13
min: 3
sum: 100


#FOR ROWS




In [24]:
arr=np.random.randint(1,30,(3,5))
print(arr)

[[19 21 29  7  4]
 [14 17 26 10  6]
 [18 21  4  8 23]]


In [32]:
print("max:",arr.max(axis=0))
print("min:",arr.min(axis=0))
print("sum:"arr.sum(axis=0))



SyntaxError: invalid syntax. Perhaps you forgot a comma? (2183196341.py, line 3)

#FOR COLUMNS

In [33]:
print("max:",arr.max(axis=1))
print("min:",arr.min(axis=1))



max: [29 26 23]
min: [4 6 4]




#SEED FUNCTION









In [2]:
np.random.seed(3)
arr=np.random.randint(1,18,(3,5))
arr

array([[11,  4,  9,  1, 11],
       [12, 10, 11,  7,  1],
       [13,  8, 15,  3,  3]])

SORTING FUNCTION

In [8]:
np.random.seed(3)
arr=np.random.randint(1,18,(3,5))

print('-'*15)
print(arr)
print('-'*15)
print(np.sort(arr,axis=1))
print('-'*15)
print(np.sort(arr,axis=0,kind='heapsort'))
print('-'*15)



---------------
[[11  4  9  1 11]
 [12 10 11  7  1]
 [13  8 15  3  3]]
---------------
[[ 1  4  9 11 11]
 [ 1  7 10 11 12]
 [ 3  3  8 13 15]]
---------------
[[11  4  9  1  1]
 [12  8 11  3  3]
 [13 10 15  7 11]]
---------------


In [10]:
print(np.sort(arr,axis=0,kind='mergesort'))

[[11  4  9  1  1]
 [12  8 11  3  3]
 [13 10 15  7 11]]


#MATRIX MULTIPLICATION

In [3]:
np.random.seed()
arr1=np.random.randint(1,10,(2,2))
arr2=np.random.randint(1,10,(2,2))

arr1

array([[6, 9],
       [3, 5]])

arr2

In [25]:
arr1.dot(arr2)


ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

In [6]:
arr2.dot(arr1)

array([[39, 61],
       [42, 64]])

In [7]:
 # P O W E R

np.random.seed()
arr1=np.random.randint(1,10,(2,2))
arr2=np.random.randint(1,10,(2,2))


print(arr1)
print(arr1**4)

In [12]:
#PERCENTILE FUNCTION

In [16]:
np.random.seed(3)
arr=np.random.randint(1,18,10)
print(arr)
print('-'*15)
arr=np.sort(arr)
print(arr)
print('-'*15)

print(np.percentile(arr,56))

[11  4  9  1 11 12 10 11  7  1]
---------------
[ 1  1  4  7  9 10 11 11 11 12]
---------------
10.040000000000001


#MEAN,VARIANCE AND STANDARD DEVIATION

np.random.seed(3)
arr=np.random.randint(1,18,10)
print(arr)
print(arr.mean())
print(arr.std())
print(arr.var())

In [22]:
#FILTERING NUMPY ARRAY

In [26]:
arr=np.arange(1,15)
print(arr)
print(arr<10)
print(arr[arr<7])


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ True  True  True  True  True  True  True  True  True False False False
 False False]
[1 2 3 4 5 6]


#TRANSPOSING AN ARRAY

In [28]:
arr=np.random.randint(1,28,(3,5))
print(arr)
print('-'*15)
print(arr.T)


[[ 9 15  2 11 25]
 [ 8 25 12  2 16]
 [17  6 21 18 22]]
---------------
[[ 9  8 17]
 [15 25  6]
 [ 2 12 21]
 [11  2 18]
 [25 16 22]]


#CONCATENATE

In [4]:
arr1=np.random.randint(1,10,(2,4))
arr2=np.random.randint(1,10,(2,4))
print(arr1)
print('-'*15)
print(arr2)
print(np.concatenate((arr1,arr2),axis=0))
print('-'*15)
print(np.concatenate((arr1,arr2),axis=1))      
      

[[8 8 2 5]
 [8 8 1 3]]
---------------
[[9 6 5 3]
 [1 2 9 4]]
[[8 8 2 5]
 [8 8 1 3]
 [9 6 5 3]
 [1 2 9 4]]
---------------
[[8 8 2 5 9 6 5 3]
 [8 8 1 3 1 2 9 4]]


#HSTACK AND VSTACK

In [9]:
print(arr1)
print(arr2)
print(np.vstack((arr1,arr2)))


[[8 8 2 5]
 [8 8 1 3]]
[[9 6 5 3]
 [1 2 9 4]]
[[8 8 2 5]
 [8 8 1 3]
 [9 6 5 3]
 [1 2 9 4]]


In [10]:
print(arr1)
print(arr2)
print(np.hstack((arr1,arr2)))


[[8 8 2 5]
 [8 8 1 3]]
[[9 6 5 3]
 [1 2 9 4]]
[[8 8 2 5 9 6 5 3]
 [8 8 1 3 1 2 9 4]]


#SPLITTING ARRAYS

In [14]:
arr=np.random.randint(1,18,(4,4))
print(arr)


[[14 14 10 13]
 [ 4  8  8 16]
 [ 9  5 14 17]
 [ 1 12 16 16]]


In [15]:
np.vsplit(arr,2)

[array([[14, 14, 10, 13],
        [ 4,  8,  8, 16]]),
 array([[ 9,  5, 14, 17],
        [ 1, 12, 16, 16]])]

#TURNNING PICS INTO NUMPY ARRAYS

In [18]:
from matplotlib.image import imread

In [22]:
img=imread('GFG.png')
img.shape

(607, 1000, 3)

In [23]:
img

array([[[0.09803922, 0.74509805, 0.92941177],
        [0.09803922, 0.74509805, 0.92941177],
        [0.09803922, 0.74509805, 0.92941177],
        ...,
        [0.09803922, 0.74509805, 0.92941177],
        [0.09803922, 0.74509805, 0.92941177],
        [0.09803922, 0.74509805, 0.92941177]],

       [[0.09803922, 0.74509805, 0.92941177],
        [0.09803922, 0.74509805, 0.92941177],
        [0.09803922, 0.74509805, 0.92941177],
        ...,
        [0.09803922, 0.74509805, 0.92941177],
        [0.09803922, 0.74509805, 0.92941177],
        [0.09803922, 0.74509805, 0.92941177]],

       [[0.09803922, 0.74509805, 0.92941177],
        [0.09803922, 0.74509805, 0.92941177],
        [0.09803922, 0.74509805, 0.92941177],
        ...,
        [0.09803922, 0.74509805, 0.92941177],
        [0.09803922, 0.74509805, 0.92941177],
        [0.09803922, 0.74509805, 0.92941177]],

       ...,

       [[0.05882353, 0.6039216 , 0.75686276],
        [0.05882353, 0.6039216 , 0.75686276],
        [0.05882353, 0

In [24]:
 np.max(img)

1.0